In [1]:
import torch 

In [2]:
randint = torch.randint(-100, 100, (6,))

In [3]:
randint

tensor([ 37, -57, -75,  25, -45, -61])

In [4]:
tensor = torch.tensor([[0.1,0.4,1.5],[3.1,4.4,5.5],[3.1,1.4,2.5]])
tensor

tensor([[0.1000, 0.4000, 1.5000],
        [3.1000, 4.4000, 5.5000],
        [3.1000, 1.4000, 2.5000]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start = -10,end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'

device

'cuda'

In [14]:
# define a probability tensor

probabilities = torch.tensor([0.1,0.9])
samples  = torch.multinomial(probabilities,num_samples=10,replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [16]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [18]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [21]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# stack the tensors
stack_tensor = torch.stack([tensor1,tensor2,tensor3])
stack_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
import torch.nn as nn

# create a tensor
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)

print(linear(sample))


tensor([-3.2797,  9.5769, -2.2888], grad_fn=<SqueezeBackward4>)


In [23]:
import torch.nn as nn
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# applying softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1,dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [24]:
# embedding the vectors

import torch.nn as nn

embedding_layer = nn.Embedding(num_embeddings=1000, embedding_dim=100)


In [25]:
import torch

# Assume input_indices is a tensor of word indices
input_indices = torch.tensor([1, 5, 3, 2, 7])

# Pass the input indices through the embedding layer
embeddings = embedding_layer(input_indices)

print(embeddings.shape)


torch.Size([5, 100])


In [28]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[5,6,7]])

print(a @ b)

print(torch.matmul(a,b))

tensor([[17, 20, 23],
        [41, 48, 55],
        [65, 76, 87]])
tensor([[17, 20, 23],
        [41, 48, 55],
        [65, 76, 87]])
