In [1]:
import torch 

In [2]:
randint = torch.randint(-100, 100, (6,))

In [3]:
randint

tensor([ 53, -17, -55,  97,  74, -40])

In [6]:
tensor = torch.tensor([[0.1,0.4,1.5],[3.1,4.4,5.5],[3.1,1.4,2.5]])
tensor

tensor([[0.1000, 0.4000, 1.5000],
        [3.1000, 4.4000, 5.5000],
        [3.1000, 1.4000, 2.5000]])

In [7]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
input = torch.empty(2,3)
input

tensor([[-7.8405e+02,  1.3116e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [15]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [16]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [17]:
logspace = torch.logspace(start = -10,end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [18]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
timing